[package]
name = "nap"
version = "0.1.0"
authors = ["Jakob Lindskog <jakob.lindskog@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indicatif = "0.15.0"
clap = "2.33.3"
